@baseURL = http://localhost:3000/pontuacoes

POST {{baseURL}}
Content-Type: application/json

{
    "jogo_id": 7,
    "jogador_id": 1,
    "pontuacao": 10
}
###

GET {{baseURL}}/ranking/7
Content-Type: application/json
###

GET {{baseURL}}/jogos/populares
Content-Type: application/json



