@baseURL = http://localhost:3000/jogos

GET {{baseURL}}
Content-Type: application/json
###


GET {{baseURL}}/4
Content-Type: application/json
###

POST {{baseURL}}
Content-Type: application/json

{
 "nome": "Cyberpunk 2077 - Phantom Liberty",
 "plataforma": "Console/PC",
 "ano_lancamento": 2024
}
###

PUT {{baseURL}}/4
Content-Type: application/json

{
 "nome": "The Legend of Zelda: Breath of the Wild (Edição Definitiva)",
 "plataforma": "Nintendo Switch",
 "ano_lancamento": 2017
}
###

DELETE {{baseURL}}/6
Content-Type: application/json