@baseURL = http://localhost:3000/jogadores

GET {{baseURL}}
Content-Type: application/json
###

GET {{baseURL}}/1
Content-Type: application/json
###

POST {{baseURL}}
Content-Type: application/json

{
 "nome": "Claudio Nadal",
 "nickname": "claudio"
}
###