"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var gerente_1 = require("./gerente");
var secretario_1 = require("./secretario");
var telefonista_1 = require("./telefonista");
var funcionario_1 = require("./funcionario");
var funcionario = new funcionario_1.Funcionario();
funcionario.nome = "João";
funcionario.salario = 2000;
funcionario.toString();
var gerente = new gerente_1.Gerente();
gerente.nome = "Artur";
gerente.salario = 10000;
gerente.nomeUsuario = "artur";
gerente.senha = "123456";
gerente.toString();
var secretario = new secretario_1.Secretario();
secretario.nome = "Marcio";
secretario.salario = 5000;
secretario.ramal = "1234";
secretario.toString();
var telefonista = new telefonista_1.Telefonista();
telefonista.nome = "Ana";
telefonista.salario = 3000;
telefonista.codigoEstacaoTrabalho = "5678";
telefonista.toString();
