"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var usuario_1 = require("./usuario");
var sistemaLogin_1 = require("./sistemaLogin");
var admin_1 = require("./admin");
var usuario = new usuario_1.Usuario();
usuario.setNome("Lucas");
usuario.setEmail("lucas@email.com");
usuario.setSenha("123456");
usuario.verificarLogin(usuario.getEmail(), usuario.getSenha());
usuario.validarEmail(usuario.getEmail());
usuario.recuperarSenha(usuario.getEmail());
var admin = new admin_1.Admin(2);
admin.setNome("Mauricio");
admin.setEmail("mauricio@email.com");
admin.setSenha("654321");
console.log(admin.getNivelAcesso());
admin.setNivelAcesso(1);
console.log(admin.getNivelAcesso());
admin.verificarLogin(admin.getEmail(), admin.getSenha());
admin.recuperarSenha(admin.getEmail());
var sistemaLogin = new sistemaLogin_1.SistemaLogin();
sistemaLogin.criarUsuario(usuario.getNome(), usuario.getEmail(), usuario.getSenha());
sistemaLogin.criarUsuario(admin.getNome(), admin.getEmail(), admin.getSenha());
console.log(sistemaLogin.login(usuario.getEmail(), usuario.getSenha()));
console.log(sistemaLogin.login(admin.getEmail(), admin.getSenha()));
sistemaLogin.recuperarSenha(usuario.getEmail());
sistemaLogin.recuperarSenha(admin.getEmail());
