"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var computador_1 = require("./computador");
var software_1 = require("./software");
var comp1 = new computador_1.Computador();
comp1.marca = "Dell";
comp1.capacidadeHD = 1000;
comp1.capacidadeRAM = 16;
comp1.freqProcessador = 3.5;
comp1.qtdNucleosProcessador = 8;
comp1.placaVideoIntegrada = true;
comp1.ligar();
comp1.abrirPrograma("VS Code", 10);
console.log(comp1.capacidadeRAM);
comp1.fecharPrograma("VS Code");
console.log(comp1.capacidadeRAM);
var comp2 = new computador_1.Computador;
comp2.marca = "Apple";
comp2.capacidadeHD = 2000;
comp2.capacidadeRAM = 16;
comp2.freqProcessador = 3.8;
comp2.qtdNucleosProcessador = 8;
comp2.placaVideoIntegrada = false;
comp2.qtdMemoriaPlacaVideo = 8;
comp2.ligar();
comp2.abrirPrograma("Safari", 50);
var sw1 = new software_1.Software;
sw1.nome = "Windows 11";
sw1.qtdHD = 11000;
sw1.qtdMemoriaRAM = 2000;
var sw2 = new software_1.Software;
sw2.nome = "Libre Office";
sw2.qtdHD = 3000;
sw2.qtdMemoriaRAM = 700;
var sw3 = new software_1.Software;
sw3.nome = "Google Chrome";
sw3.qtdHD = 1500;
sw3.qtdMemoriaRAM = 2000;
comp1.instalarSoftware(sw1);
comp1.instalarSoftware(sw2);
comp1.instalarSoftware(sw3);
