@baseURL = http://localhost:3000
@id_do_usuario = algum_id
### 1. Criar um novo usuário (POST)
POST {{baseURL}}/usuarios
Content-Type: application/json

{
 "nome": "Carlos",
 "idade": 28,
 "email": "carlos2@exemplo.com"
}
### 2. Obter todos os usuários (GET)
GET {{baseURL}}/usuarios
Content-Type: application/json
### 3. Atualizar um usuário existente (PUT)
PUT {{baseURL}}/usuarios/{{id_do_usuario}}
Content-Type: application/json

{
 "nome": "Carlos Silva",
 "idade": 30,
 "email": "carlos.silva@exemplo.com"
}
### 4. Deletar um usuário (DELETE)
DELETE {{baseURL}}/usuarios/{{id_do_usuario}}
Content-Type: application/json
